[package]
name = "clean-recently-used"
version = "0.1.0"
authors = ["Lucas Werkmeister <mail@lucaswerkmeister.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.18.1"
itertools = "0.9.0"
chrono = "0.4.15"
directories = "3.0.1"
